### ISSUE TITLE
std::sync::Arc version for multithreading

### ISSUE THREAD

**Issue by forrestthewoods** [softdevteam/cactus#15]
Really neat crate. This is exactly what I needed for a project. Unfortunately cactus uses `std::rc::Rc` with no option for `std::sync::Arc`.

It'd be really nice if Cactus provided two versions. One built on `Rc` and another built on `Arc`.

**Comment by ltratt** [comment]
Can you try the code in https://github.com/softdevteam/cactus/pull/16 and see if it works for you?

**Comment by forrestthewoods** [comment]
Hi, apologies for the slow response. You responded to my initial request so fast I feel bad!

I just verified this change works for my use case! (https://github.com/forrestthewoods/fts_gitignore_nuke)

Longer term I think it'd be nice to have the ability to use both `cactus::Cactus` and, let's say, `cactus::arc::Cactus`. For a project that may want to use both `Rc` and `Arc` in different scenarios.

For my purposes I exclusively want an `arc` version so the `cfg` works fine.

**Comment by ltratt** [comment]
Unfortunately Rust makes doing the right thing quite hard in this case (see e.g. https://users.rust-lang.org/t/support-both-rc-and-arc-in-a-library/40563/7) without hackery or code duplication :( However, I like the idea that we can plan for the future, so that using the `arc` flag makes `cactus::ArcCactus` (or whatever a good name might be) available too: that way, if there's a nicer way of doing this in the future, we can change things with minimal breakage.

**Comment by ltratt** [comment]
I think https://github.com/softdevteam/cactus/pull/18 is an adequate solution to this problem (though it uses a horrible hack) -- it allows both Arc and Rc cacti to co-exist in a single program. If that works for you, I think #18 is what we'll go with.
